### PR TITLE
Proposal for release 1.00

### PR DESCRIPTION
**Pull request by kjetilk**
Looking at the diff for 0.96, it seems this was all that was done to release the previous version, in addition to tagging it as a release.

So, I went for a bold move and called it 1.00, as it is arguable pretty stable... 

Hope you'll consider it!

### CODE REVIEW

**Comment by kjetilk** [comment]
Yeah, and BTW; it is exactly 7 years since the previous release! :fireworks:

**Comment by davidkaufman** [comment]
I dunno... maybe we should test it a bit longer.  Just to be sure 😏

**Review by msimerson — APPROVED** [review]
LGTM

**Comment by kjetilk** [comment]
Great! Now it just needs to be tagged and that tagged turned into a release on github, could you do that too, @msimerson ?

**Comment by msimerson** [comment]
Sure.

**Comment by abh** [comment]
Haha, this made my day! 22 years later and (I am guessing) trillions of SMTP connections later I guess it's as production ready as it will be.

Thanks @msimerson & @kjetilk. 😄

**Comment by msimerson** [comment]
Yeah, a 1.0 release *might* have been a wee bit overdue... thanks @kjetilk for the PR.

**Pull request merged**
