### PR TITLE
Add perms test to Qpsmtpd::DB::File::DBM::dir()

### PR DESCRIPTION
**Pull request by jaredj**

### CODE REVIEW

**Comment by jaredj** [comment]
This is ready except for the question of what to do when one of the default 'candidate directory' locations exists but is not writeable.  We currently skip such a directory with no warning.  It has been suggested to warn on this condition, however because of the (perhaps convoluted) way that we search for valid directories, this could lead to problems:

1. static directories /dir1/ and /dir2/ are being searched
2. /dir1/ has been unwriteable for months, so /dir2/greylist.dbm is being used
3. the admin notices a warning about /dir1/ being unwriteable, and "fixes" it with a chmod
4. the greylist plugin begins ignoring /dir2/greylist.dbm, creating a fresh new database in /dir1/, and suddenly greylisting a bunch of new systems and potentially causing mail flow interruption

**Comment by msimerson** [comment]
> It has been suggested to warn on this condition, however because of the (perhaps convoluted) way that we search for valid directories, this could lead to problems:

Then warn of that possibility. Not warning about existing (possibly used) dirs and letting the sysadmin do something more intelligent than you can automate is **likely** the type of silent error that's could lead to the scenario you describe.

**Comment by jaredj** [comment]
I think I can come up with something.

**Comment by jaredj** [comment]
Something seems to be broken with Coveralls preventing Travis from functioning correctly.  This does pass manual travis, though

**Pull request merged**
